### GET all vehicle
GET http://localhost:3000/vehicles

### GET vehicle by ID
GET http://localhost:3000/vehicles/674faf72808a42aad57d6500

### GET vehicle by name, model, manufacturer, or vehicle_class
GET http://localhost:3000/vehicles/search?name=localhost:3000/vehicles/search?name=Sail%20Barge


### POST create new vehicle
POST http://localhost:3000/vehicles HTTP/1.1
Content-Type: application/json

{
    "name": "Sail Barge",
    "model": "Modified Luxury Sail Barge",
    "manufacturer": "Ubrikkian Industries Custom Vehicle Division",
    "cost_in_credits": "285000",
    "length": "90",
    "max_atmosphering_speed": "100",
    "crew": "26",
    "cargo_capacity": "2000000",
    "vehicle_class": "sail barge"
}

### PUT update vehicle by ID
PUT http://localhost:3000/vehicles/674faf72808a42aad57d6500 HTTP/1.1
Content-Type: application/json

{
    "name": "Sand Crawler",
    "model": "Digger Crawler",
    "manufacturer": "Corellia Mining Corporation",
    "cost_in_credits": "150000",
    "length": "37",
    "max_atmosphering_speed": "30",
    "crew": "66",
    "cargo_capacity": "50000",
    "vehicle_class": "wheeled"
}

### DELETE vehicle by ID
DELETE http://localhost:3000/vehicles/674fafdd808a42aad57d6502